/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
        "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:47b0a938-aa18-499b-a828-3612979a78b1",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Z5R7Pg4Sn",
    "aws_user_pools_web_client_id": "4j72isovd8rpcrtncpfa6kmhdi",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
}
export default awsmobile;
